### ISSUE TITLE
Update resume data

### ISSUE THREAD

**Issue by ianpatrickhines** [ianpatrickhines/resume#29]
We are discontinuing the use of sample resume data, and replacing it with @ianpatrickhines actual resume data.

Here is a first draft:

```
# Personal Information
personal:
  name: "Ian Patrick Hines"
  title: "Hard work is hard, but it works. So work hard."
  bio: "This is sample data for demonstration purposes. Replace this with your own professional bio that captures your essence, highlights your unique value, and showcases what makes you stand out in your field."
  avatar: "👤"
  cv_link: "https://x.com/ianpatrickhines"  # For the CV link in header

# Contact Information
contact:
  email: "ian@hines.digital"
  linkedin: "https://linkedin.com/in/ianpatrickhines"
  github: "https://github.com/ianpatrickhines"
  twitter: "https://x.com/ianpatrickhines"
  website: "https://www.hines.digital"  # Optional
  phone: ""    # Optional

# Side Projects (new section)
side_projects:
  - title: "Simple Resume Template"
    year: "2025"
    description: "A simple resume template for GitHub Pages (you’re looking at it right now)."
    url: "https://github.com/ianpatrickhines/resume"
    
  # - title: "Another Side Project" 
  #   year: "2023"
  #   description: "Another example of personal work and exploration."
  #   url: "https://example.com/project2"
    
# Speaking (new section)  
# speaking:
#   - title: "Sample Conference Talk"
#     event: "Tech Conference 2024"
#     year: "2024"
#     description: "Spoke about innovative approaches to software development."
#     url: "https://example.com/talk"
    
# Features (new section)
# features:
#   - title: "Sample Feature Highlight"
#     publication: "Tech Magazine"
#     year: "2024"
#     description: "Featured article about industry trends and innovations."
#     url: "https://example.com/article"

# Experience
experience:
  - company: "Hines Digital"
    # logo: "SC"  # Can be emoji, initials, or image URL
    position: "Principal"
    period: "2015 - Present"
    location: "Remote"  # Optional
    company_url: "https://www.hines.digital"  # Optional
    description: "Hines Digital is my professional office, serving as both a consulancy and a holding company as I found and acquire profitable online businesses."
  
  - company: "Conduit Street Services, LLC"
    # logo: "PS"
    position: "Founder & CEO"
    period: "2024 - Present"
    location: "Remote"  # Optional
    company_url: "https://conduitstreetservices.com"  # Optional
    description: "Conduit Street Services, LLC supports political committees with email & text messaging fundraising services. Since 2024, we’ve raisesed more than $2.5 million online."

  - company: "MD5 Data, LLC"
    # logo: "PS"
    position: "Founder & CEO"
    period: "2024 - Present"
    location: "Remote"  # Optional
    company_url: "https://md5data.com"  # Optional
    description: "MD5 Data, LLC provides compliant political data services."

  - company: "Freelance"
    # logo: "PS"
    position: "Certified NationBuilder Expert"
    period: "2013 - 2015"
    location: "Remote"  # Optional
    description: "Provided NationBuilder consulting services to campaigns & causes."

# Education
education:
  - institution: "University of Baltimore"
    logo: "🎓"
    degree: "Master of Public Administration"
    period: "2010"
    description: "Focused on budgeting, statistics, and government & non-profit management."

  - institution: "McDaniel College"
    logo: "🎓"
    degree: "Bachelor of Arts in Political Science"
    period: "2016 - 2020"
    description: "Graduated in three years. Focused on political science with an emphasis on US constitutional law and state & local government."

# Projects
# projects:
#   - name: "Sample Project One"
#     year: "2024"
#     description: "Sample project entry. A brief description of your project, what technologies you used, and what problems it solves. Keep it concise but informative."
#     url: "https://sampleproject1.com"  # Optional main project URL
#     image: "https://via.placeholder.com/200x100/cccccc/666666?text=Project+1"  # 200x100px image
#     links:
#       - name: "Live Demo"
#         url: "#"
#         icon: "🔗"
#       - name: "GitHub"
#         url: "#"
#         icon: "🐙"
  
#   - name: "Sample Project Two"
#     year: "2023"
#     description: "Another sample project entry showcasing different skills and technologies. Highlight the impact and results achieved."
#     url: "https://sampleproject2.com"  # Optional main project URL
#     image: "https://via.placeholder.com/200x100/cccccc/666666?text=Project+2"  # 200x100px image
#     links:
#       - name: "Live Demo"
#         url: "#"
#         icon: "🔗"
#       - name: "GitHub"
#         url: "#"
#         icon: "🐙"

# Awards (Optional)
awards:
  - title: "Certified NationBuilder Architect"
    organization: "NationBuilder"
    year: "2013"
    description: "Certified to build custom websites and themes for multiple NationBuilder customers."

  - title: "Certified NationBuilder Expert"
    organization: "NationBuilder"
    year: "2013"
    description: "Certified to support customers’ day to day use of NationBuilder."

# Site Settings
settings:
  show_awards: true      # Set to false to hide awards section
  show_education: true   # Set to false to hide education section
  theme_color: "#1d9bf0" # Main accent color for light theme
  dark_theme_color: "#1d9bf0" # Main accent color for dark theme (optional, defaults to lighter version)
```

Notice that I commented out some sections I intend to revisit, removed some sections we are no longer using, and updated colors. I also want you to load the attached image as the avatar photo. 

You may want to slightly modify the YAML schema so that `projects` is more correctly called `client_projects`. 

![Image](https://github.com/user-attachments/assets/0d6eba36-25da-44cb-a47e-7babd327c1ad)
